---
site_name: "geochem-rf-linkml"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2:
      version: 11.4.1
nav:
  - Home: index.md
  - Schema: elements/index.md
  - ER Diagram: elements/erdiagram.md
  - Downloads: downloads.md
  - About: about.md
site_url: https://sierra-moxon.github.io/geochem-rf-linkml
repo_url: https://github.com/sierra-moxon/geochem-rf-linkml
markdown_extensions:
  - tables
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
